export default {
    getSampleCommissionRateRequest: () => {
        return {
            "commissionRate": "20.00",
            "commissionRateDiscount": null,
            "commissionRateDiscountCodes": null,
            "commissionRateDiscountScope": "all",
            "commissionRateDiscountSplit": "100.00",
            "commissionRateFixedType": "deduct_by",
            "commissionRateType": "percentage",
            "saleItem": {
                "allocation": 0,
                "commercialInvoicePrice": null,
                "tax": 0,
                "price": 20,
                "subtotal": 200,
                "id": 6244415,
                "saleId": 3213320,
                "dropshipProviderId": null,
                "warehouseId": null,
                "bundleSaleItemId": null,
                "cloneSaleItemId": null,
                "externalId": "line-external-id",
                "externalVariantId": "",
                "orderRouting": "automated",
                "manualRouting": null,
                "quantityCancelled": 0,
                "quantityRefunded": 0,
                "discounts": null,
                "discount": null,
                "channelPrice": "10.00",
                "channelCompareAtPrice": "0.00",
                "costPrice": null,
                "location": null,
                "preventDuplicates": false,
                "unallocated": false,
                "companyId": 2729,
                "variantId": 7290781,
                "locked": true,
                "name": "line-item-name",
                "notes": null,
                "quantity": 10,
                "taxable": true,
                "taxRate": null,
                "inventoryProcessed": 0,
                "quantityInvoiced": 0,
                "quantityReturned": 0,
                "bundleQuantity": 0,
                "isBundle": false,
                "properties": [
                    {
                        "name": "Gift Note",
                        "value": "Hello from UK"
                    }
                ],
                "createdAt": "2021-10-03T23:04:20.917Z",
                "updatedAt": "2021-10-03T23:04:20.917Z",
                "variant": {
                    "imagesMapped": [],
                    "images": [],
                    "displayName": "39412060225730",
                    "costPrice": 5,
                    "commissionRate": 0,
                    "commissionRateRouting": "dropship_provider",
                    "commissionRateType": "percentage",
                    "companyId": 2729,
                    "dropshipProviderId": null,
                    "dropshipProviderAddressId": null,
                    "dropshipProviderMapping": "brand_name",
                    "fulfillmentPolicy": "vendor_default",
                    "grams": 5,
                    "id": 7290781,
                    "inventoryQuantity": 0,
                    "noInventoryPolicy": "replenish",
                    "orderSplitting": "default",
                    "productType": "",
                    "sku": "39412060225730",
                    "tags": [],
                    "vendorId": 75094,
                    "vendor": {
                        "email": null,
                        "id": 75094,
                        "warehouseId": null,
                        "dropshipProcessing": "dropship_provider",
                        "specifyDropshipProviders": true,
                        "orderEmail": null,
                        "fulfillmentPolicy": "dropship",
                        "warehouseRouting": "select"
                    },
                    "inventory_feed_variants": [
                        {
                            "images": [],
                            "costPrice": 5,
                            "retailPrice": 0,
                            "compareAtPrice": 0,
                            "id": 167582347,
                            "inventoryFeedId": 12814,
                            "inventoryQuantity": 7,
                            "status": "connected"
                        }
                    ]
                }
            },
            "variant": {
                "imagesMapped": [],
                "images": [],
                "displayName": "39412060225730",
                "costPrice": 5,
                "commissionRate": 0,
                "commissionRateRouting": "dropship_provider",
                "commissionRateType": "percentage",
                "companyId": 2729,
                "dropshipProviderId": null,
                "dropshipProviderAddressId": null,
                "dropshipProviderMapping": "brand_name",
                "fulfillmentPolicy": "vendor_default",
                "grams": 5,
                "id": 7290781,
                "inventoryQuantity": 0,
                "noInventoryPolicy": "replenish",
                "orderSplitting": "default",
                "productType": "",
                "sku": "39412060225730",
                "tags": [],
                "vendorId": 75094,
                "vendor": {
                    "email": null,
                    "id": 75094,
                    "warehouseId": null,
                    "dropshipProcessing": "dropship_provider",
                    "specifyDropshipProviders": true,
                    "orderEmail": null,
                    "fulfillmentPolicy": "dropship",
                    "warehouseRouting": "select"
                },
                "inventory_feed_variants": [
                    {
                        "images": [],
                        "costPrice": 5,
                        "retailPrice": 0,
                        "compareAtPrice": 0,
                        "id": 167582347,
                        "inventoryFeedId": 12814,
                        "inventoryQuantity": 7,
                        "status": "connected"
                    }
                ]
            }
        }
    },
    getSampleCustomerInfoForSale: () => {
        return {
            "billingFullName": "Test Customer",
            "shippingFullName": "Test Customer",
            "total": 0,
            "subtotal": 0,
            "discounts": 0,
            "tax": 0,
            "combinedTaxRate": "0.0000",
            "billingName": null,
            "billingAddressLineOne": "123 N University Blvd",
            "billingAddressLineTwo": "111",
            "billingCity": "Bari",
            "billingState": "BA",
            "billingCountry": "IT",
            "billingZip": "11000",
            "shippingName": null,
            "shippingAddressLineOne": "123 N university",
            "shippingAddressLineTwo": "111",
            "shippingCity": "Rome",
            "shippingState": "BA",
            "shippingCountry": "IT",
            "shippingZip": "11000",
            "receiverName": null,
            "receiverAddressLineOne": null,
            "receiverAddressLineTwo": null,
            "receiverCity": null,
            "receiverState": null,
            "receiverCountry": null,
            "receiverZip": null,
            "id": 3213320,
            "companyId": 2729,
            "userId": null,
            "priceListId": 3172,
            "channelId": 4707,
            "warehouseId": 2999,
            "customerId": 1975036,
            "saleDiscountCodeId": null,
            "saleId": null,
            "resellerId": null,
            "cloneReason": null,
            "externalId": "99925",
            "lastPurchaseReference": 1,
            "lastSaleReturnReference": 0,
            "lastFulfillmentReference": 0,
            "status": "finalized",
            "internalNotes": null,
            "inventoryStatus": "notFulfilled",
            "cancelReason": null,
            "channelCancelledAt": null,
            "shipstationId": null,
            "paid": null,
            "dropshipProblems": [],
            "resellerStripeChargeId": null,
            "resellerPayee": "reseller",
            "adjustmentReasonId": null,
            "reference": "10011",
            "locked": true,
            "finalized": false,
            "cancelled": false,
            "cancelledAt": null,
            "dateOrdered": "2021-10-03T23:04:18.738Z",
            "taxCalculation": "default",
            "taxShipping": true,
            "taxIncluded": false,
            "weight": 0,
            "quantity": 0,
            "stateTaxRate": null,
            "cityTaxRate": null,
            "countyTaxRate": null,
            "districtTaxRate": null,
            "stateTaxLocation": null,
            "cityTaxLocation": null,
            "countyTaxLocation": null,
            "paymentStatus": "notPaid",
            "invoiceStatus": "notInvoiced",
            "returnStatus": "notReturned",
            "cancellationStatus": "none",
            "notes": "Test",
            "customerReference": null,
            "tags": [
                "dropship"
            ],
            "billingFirstName": "Test",
            "billingLastName": "Customer",
            "shippingFirstName": "Test",
            "shippingLastName": "Customer",
            "invalidShippingAddress": false,
            "shippingAddressMessage": null,
            "invalidBillingAddress": false,
            "billingAddressMessage": null,
            "createdAt": "2021-10-03T23:04:18.738Z",
            "updatedAt": "2021-10-03T23:05:58.439Z",
            "muteError": false,
            "adminNotes": null,
            "intercomMessageId": null
        }
    }
}