export default {
    getSampleCommissionRateRequest: () => {
        return {
            "commissionRate": "20.00",
            "commissionRateDiscount": null,
            "commissionRateDiscountCodes": null,
            "commissionRateDiscountScope": "all",
            "commissionRateDiscountSplit": "100.00",
            "commissionRateFixedType": "deduct_by",
            "commissionRateType": "percentage",
            "saleItem": {
                "allocation": 0,
                "commercialInvoicePrice": null,
                "tax": 0,
                "price": 20,
                "subtotal": 200,
                "id": 6244415,
                "saleId": 3213320,
                "dropshipProviderId": null,
                "warehouseId": null,
                "bundleSaleItemId": null,
                "cloneSaleItemId": null,
                "externalId": "line-external-id",
                "externalVariantId": "",
                "orderRouting": "automated",
                "manualRouting": null,
                "quantityCancelled": 0,
                "quantityRefunded": 0,
                "discounts": null,
                "discount": null,
                "channelPrice": "10.00",
                "channelCompareAtPrice": "0.00",
                "costPrice": null,
                "location": null,
                "preventDuplicates": false,
                "unallocated": false,
                "companyId": 2729,
                "variantId": 7290781,
                "locked": true,
                "name": "line-item-name",
                "notes": null,
                "quantity": 10,
                "taxable": true,
                "taxRate": null,
                "inventoryProcessed": 0,
                "quantityInvoiced": 0,
                "quantityReturned": 0,
                "bundleQuantity": 0,
                "isBundle": false,
                "properties": [
                    {
                        "name": "Gift Note",
                        "value": "Hello from UK"
                    }
                ],
                "createdAt": "2021-10-03T23:04:20.917Z",
                "updatedAt": "2021-10-03T23:04:20.917Z",
                "variant": {
                    "imagesMapped": [],
                    "images": [],
                    "displayName": "39412060225730",
                    "costPrice": 5,
                    "commissionRate": 0,
                    "commissionRateRouting": "dropship_provider",
                    "commissionRateType": "percentage",
                    "companyId": 2729,
                    "dropshipProviderId": null,
                    "dropshipProviderAddressId": null,
                    "dropshipProviderMapping": "brand_name",
                    "fulfillmentPolicy": "vendor_default",
                    "grams": 5,
                    "id": 7290781,
                    "inventoryQuantity": 0,
                    "noInventoryPolicy": "replenish",
                    "orderSplitting": "default",
                    "productType": "",
                    "sku": "39412060225730",
                    "tags": [],
                    "vendorId": 75094,
                    "vendor": {
                        "email": null,
                        "id": 75094,
                        "warehouseId": null,
                        "dropshipProcessing": "dropship_provider",
                        "specifyDropshipProviders": true,
                        "orderEmail": null,
                        "fulfillmentPolicy": "dropship",
                        "warehouseRouting": "select"
                    },
                    "inventory_feed_variants": [
                        {
                            "images": [],
                            "costPrice": 5,
                            "retailPrice": 0,
                            "compareAtPrice": 0,
                            "id": 167582347,
                            "inventoryFeedId": 12814,
                            "inventoryQuantity": 7,
                            "status": "connected"
                        }
                    ]
                }
            },
            "variant": {
                "imagesMapped": [],
                "images": [],
                "displayName": "39412060225730",
                "costPrice": 5,
                "commissionRate": 0,
                "commissionRateRouting": "dropship_provider",
                "commissionRateType": "percentage",
                "companyId": 2729,
                "dropshipProviderId": null,
                "dropshipProviderAddressId": null,
                "dropshipProviderMapping": "brand_name",
                "fulfillmentPolicy": "vendor_default",
                "grams": 5,
                "id": 7290781,
                "inventoryQuantity": 0,
                "noInventoryPolicy": "replenish",
                "orderSplitting": "default",
                "productType": "",
                "sku": "39412060225730",
                "tags": [],
                "vendorId": 75094,
                "vendor": {
                    "email": null,
                    "id": 75094,
                    "warehouseId": null,
                    "dropshipProcessing": "dropship_provider",
                    "specifyDropshipProviders": true,
                    "orderEmail": null,
                    "fulfillmentPolicy": "dropship",
                    "warehouseRouting": "select"
                },
                "inventory_feed_variants": [
                    {
                        "images": [],
                        "costPrice": 5,
                        "retailPrice": 0,
                        "compareAtPrice": 0,
                        "id": 167582347,
                        "inventoryFeedId": 12814,
                        "inventoryQuantity": 7,
                        "status": "connected"
                    }
                ]
            }
        }
    },
    getSampleCustomerInfoForSale: () => {
        return {
            "billingFullName": "Test Customer",
            "shippingFullName": "Test Customer",
            "total": 0,
            "subtotal": 0,
            "discounts": 0,
            "tax": 0,
            "combinedTaxRate": "0.0000",
            "billingName": null,
            "billingAddressLineOne": "123 N University Blvd",
            "billingAddressLineTwo": "111",
            "billingCity": "Bari",
            "billingState": "BA",
            "billingCountry": "IT",
            "billingZip": "11000",
            "shippingName": null,
            "shippingAddressLineOne": "123 N university",
            "shippingAddressLineTwo": "111",
            "shippingCity": "Rome",
            "shippingState": "BA",
            "shippingCountry": "IT",
            "shippingZip": "11000",
            "receiverName": null,
            "receiverAddressLineOne": null,
            "receiverAddressLineTwo": null,
            "receiverCity": null,
            "receiverState": null,
            "receiverCountry": null,
            "receiverZip": null,
            "id": 3213320,
            "companyId": 2729,
            "userId": null,
            "priceListId": 3172,
            "channelId": 4707,
            "warehouseId": 2999,
            "customerId": 1975036,
            "saleDiscountCodeId": null,
            "saleId": null,
            "resellerId": null,
            "cloneReason": null,
            "externalId": "99925",
            "lastPurchaseReference": 1,
            "lastSaleReturnReference": 0,
            "lastFulfillmentReference": 0,
            "status": "finalized",
            "internalNotes": null,
            "inventoryStatus": "notFulfilled",
            "cancelReason": null,
            "channelCancelledAt": null,
            "shipstationId": null,
            "paid": null,
            "dropshipProblems": [],
            "resellerStripeChargeId": null,
            "resellerPayee": "reseller",
            "adjustmentReasonId": null,
            "reference": "10011",
            "locked": true,
            "finalized": false,
            "cancelled": false,
            "cancelledAt": null,
            "dateOrdered": "2021-10-03T23:04:18.738Z",
            "taxCalculation": "default",
            "taxShipping": true,
            "taxIncluded": false,
            "weight": 0,
            "quantity": 0,
            "stateTaxRate": null,
            "cityTaxRate": null,
            "countyTaxRate": null,
            "districtTaxRate": null,
            "stateTaxLocation": null,
            "cityTaxLocation": null,
            "countyTaxLocation": null,
            "paymentStatus": "notPaid",
            "invoiceStatus": "notInvoiced",
            "returnStatus": "notReturned",
            "cancellationStatus": "none",
            "notes": "Test",
            "customerReference": null,
            "tags": [
                "dropship"
            ],
            "billingFirstName": "Test",
            "billingLastName": "Customer",
            "shippingFirstName": "Test",
            "shippingLastName": "Customer",
            "invalidShippingAddress": false,
            "shippingAddressMessage": null,
            "invalidBillingAddress": false,
            "billingAddressMessage": null,
            "createdAt": "2021-10-03T23:04:18.738Z",
            "updatedAt": "2021-10-03T23:05:58.439Z",
            "muteError": false,
            "adminNotes": null,
            "intercomMessageId": null
        }
    },
    getSampleVendorSubmissionRequest: () => {
        return {
            "packingSlip": "https://s3.amazonaws.com/jetti-development/258.pdf",
            "dropshipments": [
                {
                    "labelFileFormat": "pdf",
                    "labelUrl": "https://shippo-delivery-east.s3.amazonaws.com/7a1649e0f8724f3fbd5f1ee914f6a3dd.pdf?Signature=ybrT7WlnCp0%2FMU3eTmNgY8aHThE%3D&Expires=1551827128&AWSAccessKeyId=AKIAJGLCC5MYLLWIG42A",
                    "trackingUrl": "https://tools.usps.com/go/TrackConfirmAction_input?origTrackNum=92055901755477000000000015",
                    "trackingCompany": "USPS",
                    "trackingNumber": "92055901755477000000000015",
                    "id": 419,
                    "packingDepth": 0,
                    "packingWidth": 0,
                    "packingHeight": 0,
                    "grams": 0,
                    "price": 0
                }
            ],
            "purchaseItems": [
                {
                    "variant": {
                        "inventory_feed_variants": [],
                        "images": [
                            "https://cdn.shopify.com/s/files/1/1022/4011/products/DB05_CamoMarbledSandals.jpeg?v=1444655712"
                        ],
                        "vendorSku": null,
                        "barcode": null,
                        "sku": "DB5-CAM-9",
                        "id": 457,
                        "costPrice": 0
                    },
                    "quantityInvoiced": 1,
                    "inventoryProcessed": 1,
                    "quantity": 1,
                    "name": "Doc Black Camo Sandal",
                    "variantId": 457,
                    "companyId": 1,
                    "id": 316,
                    "subtotal": 0,
                    "price": 0,
                    "tax": 0,
                    "returnStatus": "notReturned",
                    "invoiceStatus": "invoiced",
                    "inventoryStatus": "received",
                    "isComponent": false
                }
            ],
            "sale": {
                "customer": {
                    "phone": "+447824449752",
                    "lastName": "Smith",
                    "firstName": "Jack",
                    "email": "jack@jetti.io"
                },
                "dateOrdered": "2018-03-05T23:05:09.000Z",
                "externalId": null,
                "reference": "10234",
                "id": 254,
                "combinedTaxRate": 0,
                "tax": 0,
                "discounts": 0,
                "subtotal": 0,
                "total": 0
            },
            "purchase": {
                "dropship_provider_id": 1,
                "company_id": 1,
                "purchase_status_id": null,
                "updatedAt": "2018-03-05T23:05:12.599Z",
                "createdAt": "2018-03-05T23:05:12.599Z",
                "reminderLastSent": null,
                "reminderSent": false,
                "vendorEndpointHeaders": null,
                "vendorEndpointResponse": null,
                "vendorEndpointFormat": null,
                "vendorReceivedReference": null,
                "vendorReceivedId": null,
                "vendorReceivedStatus": "notSent",
                "vendorReference": null,
                "approved": true,
                "dropshipNotes": null,
                "isDropship": true,
                "purchaseType": "automated_dropship",
                "lastGoodsReceiptReference": 0,
                "lastDropshipmentReference": 1,
                "lastPurchaseInvoiceReference": 1,
                "files": null,
                "purchaseStatusId": null,
                "saleId": 254,
                "purchaseId": null,
                "dropshipProviderId": 1,
                "vendorId": null,
                "warehouseId": null,
                "priceListId": 2,
                "receiverZip": null,
                "receiverCountry": null,
                "receiverState": null,
                "receiverCity": null,
                "receiverAddressLineTwo": null,
                "receiverAddressLineOne": null,
                "receiverName": null,
                "shippingZip": "94105",
                "shippingCountry": "US",
                "shippingState": "CALIFORNIA",
                "shippingCity": "San Francisco",
                "shippingAddressLineTwo": null,
                "shippingAddressLineOne": "181 Fremont St",
                "shippingName": "Jack Inc",
                "billingZip": "94105",
                "billingCountry": "US",
                "billingState": "CA",
                "billingCity": "San Francisco",
                "billingAddressLineTwo": null,
                "billingAddressLineOne": "181 Fremont St",
                "billingName": "jetti-imac-2",
                "billingAddressMessage": null,
                "invalidBillingAddress": false,
                "shippingAddressMessage": false,
                "invalidShippingAddress": false,
                "shippingLastName": null,
                "shippingFirstName": null,
                "billingLastName": null,
                "billingFirstName": null,
                "tags": null,
                "customerReference": null,
                "notes": null,
                "cancellationStatus": "none",
                "returnStatus": "notReturned",
                "invoiceStatus": "invoiced",
                "paymentStatus": "notPaid",
                "countyTaxLocation": null,
                "cityTaxLocation": null,
                "stateTaxLocation": null,
                "districtTaxRate": null,
                "countyTaxRate": null,
                "cityTaxRate": null,
                "stateTaxRate": null,
                "quantity": 0,
                "weight": 0,
                "taxIncluded": false,
                "taxShipping": true,
                "dateOrdered": "2018-03-05T23:05:12.000Z",
                "cancelledAt": null,
                "cancelled": false,
                "finalized": true,
                "locked": false,
                "reference": "10234-01",
                "adjustmentReasonId": null,
                "companyId": 1,
                "id": 258,
                "combinedTaxRate": 0,
                "tax": 0,
                "discounts": 0,
                "subtotal": 0,
                "total": 0,
                "inventoryStatus": "shipped"
            }
        }
    },
    getSampleCustomerUUID: () => {
        return {
            "uuid": "40c094d0-fbb0-3493-98a4-63ba9ead346d"
        }
    }
}